package javaapplication1;


import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;


public class existing extends javax.swing.JFrame {

    protected static int id;
    
    
    public existing() {
        initComponents();
          tid.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        lid = new javax.swing.JLabel();
        lsex = new javax.swing.JLabel();
        tsex = new javax.swing.JTextField();
        tid = new javax.swing.JTextField();
        lname = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        lincome = new javax.swing.JLabel();
        lincomeo = new javax.swing.JLabel();
        tincome = new javax.swing.JTextField();
        tincomeo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tded = new javax.swing.JTextField();
        bshow = new javax.swing.JButton();
        lgincome = new javax.swing.JLabel();
        tgincome = new javax.swing.JTextField();
        ltamount = new javax.swing.JLabel();
        ltax = new javax.swing.JLabel();
        lrate = new javax.swing.JLabel();
        trate = new javax.swing.JTextField();
        ttamount = new javax.swing.JTextField();
        ttax = new javax.swing.JTextField();
        bdownload = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(220, 214, 213));

        lid.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 24)); // NOI18N
        lid.setText("USER ID");

        lsex.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 24)); // NOI18N
        lsex.setText("SEX");

        tid.setFont(new java.awt.Font("Ubuntu Medium", 1, 15)); // NOI18N
        tid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tidFocusLost(evt);
            }
        });
        tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidActionPerformed(evt);
            }
        });

        lname.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 24)); // NOI18N
        lname.setText("NAME");

        tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnameActionPerformed(evt);
            }
        });

        lincome.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 24)); // NOI18N
        lincome.setText("INCOME FROM SALARY");

        lincomeo.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 24)); // NOI18N
        lincomeo.setText("INCOME FROM OTHER SOURCES");

        jLabel1.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 24)); // NOI18N
        jLabel1.setText("DEDUCTIONS");

        bshow.setBackground(new java.awt.Color(142, 155, 154));
        bshow.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 18)); // NOI18N
        bshow.setForeground(new java.awt.Color(87, 50, 227));
        bshow.setText("SHOW");
        bshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bshowActionPerformed(evt);
            }
        });

        lgincome.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 24)); // NOI18N
        lgincome.setText("TOTAL GROSS INCOME");

        ltamount.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 24)); // NOI18N
        ltamount.setText("TAXABLE AMOUNT");

        ltax.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 24)); // NOI18N
        ltax.setText("INCOME TAX");

        lrate.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 24)); // NOI18N
        lrate.setText("INCOME RATE");

        bdownload.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 18)); // NOI18N
        bdownload.setForeground(new java.awt.Color(87, 50, 227));
        bdownload.setText("DOWNLOAD");
        bdownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdownloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lincomeo)
                            .addComponent(jLabel1)
                            .addComponent(lgincome)
                            .addComponent(ltamount)
                            .addComponent(ltax)
                            .addComponent(lrate))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tincomeo)
                            .addComponent(tded)
                            .addComponent(tgincome)
                            .addComponent(ttamount)
                            .addComponent(trate)
                            .addComponent(ttax))
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lsex, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lname)
                            .addComponent(lincome)
                            .addComponent(lid, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(bshow, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tsex, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 70, Short.MAX_VALUE))
                                    .addComponent(tincome))
                                .addGap(75, 75, 75))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bdownload, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bshow, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdownload, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lsex)
                    .addComponent(tsex, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lincome)
                    .addComponent(tincome, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lincomeo)
                    .addComponent(tincomeo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tded, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tgincome, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lgincome))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(trate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addComponent(lrate))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ltamount)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ttamount, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ttax, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ltax))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidActionPerformed
        
    }//GEN-LAST:event_tidActionPerformed

    private void bshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bshowActionPerformed
        id=Integer.valueOf(tid.getText());
        
         Connection con = null;
        ResultSet rs=null;  
       PreparedStatement stmt=null;
        try{  
              Class.forName("com.mysql.jdbc.Driver");  
              con=DriverManager.getConnection("jdbc:mysql://localhost:3306/incometable","root","root");  
               stmt =con.prepareStatement("SELECT *FROM userrecord WHERE USER_ID=?");
               stmt.setInt(1,Integer.valueOf(tid.getText()));
                rs = stmt.executeQuery();
                
                if(rs.next()){
                {
                tname.setText(rs.getString("NAME"));
                tsex.setText(rs.getString("SEX"));
                tincome.setText(rs.getString("INCOME_FROM_SALARY"));
                tincomeo.setText(rs.getString("INCOME_FROM_OTHER_SOURCES"));
                tded.setText(rs.getString("DEDUCTIONS"));
                tgincome.setText(rs.getString("TOTAL_GROSS_INCOME"));
                ttamount.setText(rs.getString("TAXABLE_AMOUNT"));
                trate.setText(rs.getString("INCOME_RATE"));
                ttax.setText(rs.getString("INCOME_TAX"));
                }}
               else{
                       
                      JOptionPane.showMessageDialog(null,"Data not found!!");
               
                    }

            }catch(Exception e)
            {
                System.out.println(e);
            } 
              finally
        {
            //STEP 5 : Closing The DB Resources
            try
            {
                if(rs!=null)
                {
                    rs.close();
                    rs=null;
                }
            }
            catch (SQLException e)
            {
                e.printStackTrace();
            }
            //Closing the PreparedStatement object
             
            try
            {
                if(stmt!=null)
                {
                    stmt.close();
                    stmt=null;
                }
            }
            catch (SQLException e)
            {
                e.printStackTrace();
            }
  
            //Closing the Connection object
  
            try
            {
                if(con!=null)
                {
                    con.close();
                    con=null;
                }
            }
            catch (SQLException e)
            {
                e.printStackTrace();
            }
            tname.setEditable(false);
                tgincome.setEditable(false);
                tincomeo.setEditable(false);
                tsex.setEditable(false);
                tded.setEditable(false);
                tincome.setEditable(false);
                ttamount.setEditable(false);
                ttax.setEditable(false);
                trate.setEditable(false);

    }//GEN-LAST:event_bshowActionPerformed
    }
    private void tnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnameActionPerformed

    private void tidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tidFocusGained
        tid.setForeground(Color.blue);  // TODO add your handling code here:
    }//GEN-LAST:event_tidFocusGained

    private void tidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tidFocusLost
        tid.setForeground(Color.black); // TODO add your handling code here:
    }//GEN-LAST:event_tidFocusLost

    private void bdownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdownloadActionPerformed
        // TODO add your handling code here:
        id=Integer.valueOf(tid.getText());
         pdfGenerator pdf=new pdfGenerator();
        pdf.pdfgen(id);
    }//GEN-LAST:event_bdownloadActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(existing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(existing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(existing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(existing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new existing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdownload;
    private javax.swing.JButton bshow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JLabel lgincome;
    private javax.swing.JLabel lid;
    private javax.swing.JLabel lincome;
    private javax.swing.JLabel lincomeo;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel lrate;
    private javax.swing.JLabel lsex;
    private javax.swing.JLabel ltamount;
    private javax.swing.JLabel ltax;
    private javax.swing.JTextField tded;
    private javax.swing.JTextField tgincome;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tincome;
    private javax.swing.JTextField tincomeo;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField trate;
    private javax.swing.JTextField tsex;
    private javax.swing.JTextField ttamount;
    private javax.swing.JTextField ttax;
    // End of variables declaration//GEN-END:variables
}
